### ISSUE TITLE
Fatal Error While Using Make

### ISSUE THREAD

**Issue by TSEG6** [danielryb/MMRecompSongUtils#1]
![image](https://github.com/user-attachments/assets/2f4e486b-9375-42c4-87d9-66cc8384116c)

**Comment by danielryb** [comment]
Thanks for feedback! This is an object file. It's created by decomp during the process of building a rom, when game assets get extracted from an original rom.

I've replaced this include with a necessary declaration in the latest commit (45e27f0), so building the decomp won't be required anymore.
